name       : bitmessage
version    : 0.6.2
release    : 3
source     :
    - https://github.com/Bitmessage/PyBitmessage/archive/v0.6.2.tar.gz : bc209725ef7c1b913ec8560557e3e862a11f664bd8c5fd2eea5adcd915acc2c6
license    : MIT
component  : network.im
summary    : Bitmessage is a P2P communications protocol used to send encrypted messages.
description: |
    Bitmessage is a P2P communications protocol used to send encrypted messages to another person or to many subscribers.
builddeps  :
    - python-msgpack
    - python-qt4
    - python-setuptools
rundeps    :
    - python-msgpack
    - python-qt4
setup      : |
    sed -i '162,167d' setup.py
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 desktop/pybitmessage.desktop $installdir/usr/share/applications/pybitmessage.desktop
    install -Dm00644 desktop/can-icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/pybitmessage.svg
