name       : bitmessage
version    : 0.6.0
release    : 2
source     :
    - https://github.com/Bitmessage/PyBitmessage/archive/v0.6.0.tar.gz : 3bee5ca3fe42a95a0bf1f9f7285904e18ae56b0189048968a5257676f25adc08
license    : MIT
component  : network.im
summary    : Bitmessage is a P2P communications protocol used to send encrypted messages.
description: |
    Bitmessage is a P2P communications protocol used to send encrypted messages to another person or to many subscribers.
builddeps :
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - python-qt4
rundeps  :
    - openssl
    - python-qt4
setup  : |
    %configure
build  : |
    %make
install  : |
    %make_install PREFIX="/usr"
    # Desktop Swapping
    rm $installdir/usr/bin/pybitmessage
    echo '#!/bin/sh
    cd /usr/share/pybitmessage
    exec python2 bitmessagemain.py' > $installdir/usr/bin/pybitmessage
    chmod +x $installdir/usr/bin/pybitmessage
    # Remove empty dirs
    rmdir --ignore-fail-on-non-empty -p $installdir/usr/share/icons/hicolor/scalable/apps
    rmdir $installdir/usr/share/pixmaps
